//
//  RegisterPresenter.swift
//  Eventize
//
//  Created by JP Giarrante on 09/09/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegisterPresentationLogic {
    func presentSomething(response: Register.Something.Response)
}

final class RegisterPresenter: RegisterPresentationLogic {
    weak var viewController: RegisterDisplayLogic?

    // MARK: Parse and calc respnse from RegisterInteractor and send simple view model to RegisterViewController to be displayed

    func presentSomething(response: Register.Something.Response) {
        let viewModel = Register.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
//
//    func presentSomethingElse(response: Register.SomethingElse.Response) {
//        let viewModel = Register.SomethingElse.ViewModel()
//        viewController?.displaySomethingElse(viewModel: viewModel)
//    }
}
