//
//  EventPresenter.swift
//  Eventize
//
//  Created by JP Giarrante on 09/09/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EventPresentationLogic {
    func presentEvent(response: Event.EventDetails.Response)
}

final class EventPresenter: EventPresentationLogic {
    weak var viewController: EventDisplayLogic?

    // MARK: Parse and calc respnse from EventInteractor and send simple view model to EventViewController to be displayed

    func presentEvent(response: Event.EventDetails.Response) {
        let viewModel = Event.EventDetails.ViewModel(event: response.event, eventDetails: response.eventDetails)
        viewController?.displayEvent(viewModel: viewModel)
    }
}
