//
//  EventModels.swift
//  Eventize
//
//  Created by JP Giarrante on 09/09/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Event
{
    typealias EventObject = Events.EventObject
    typealias CellViewModel = Events.EventList.CellViewModel
    
    // MARK: Use cases

    enum EventDetails {
        struct Request {
            let eventUuid: Int
        }

        struct Response {
            let event: EventObject?
        }
        
        struct ViewModel {
            let event: EventObject
        }
        
        struct CellViewModel {
            struct Label {
                let image: UIImage?
                let text: String
            }
            
            let image: UIImage?
            let title: String
            let address: String
            let price: Double
            let extraInfo: String?
            let labels: [Label]?
        }
    }
    
//    enum SomethingElse
//    {
//        struct Request
//        {
//
//        }
//
//        struct Response
//        {
//
//        }
//
//        struct ViewModel
//        {
//
//        }
//    }
}
