//
//  EventModels.swift
//  Eventize
//
//  Created by JP Giarrante on 09/09/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Event {
    typealias EventObject = Events.EventObject
    
    enum EventDetails {
        struct Request {
            let eventUuid: Int
        }

        struct Response {
            let event: EventObject
            let eventDetails: DetailsContent?
        }
        
        struct ViewModel {
            let event: EventObject
            let eventDetails: DetailsContent?
        }
    }
    
    struct DetailsContent: Codable {
        let description: String?
        
        private enum CodingKeys: String, CodingKey {
            case description
        }
    }
    
    enum EventFetchError: Error {
        case networkError
        case dataParsingError
    }
}
