//
//  EventRouter.swift
//  Eventize
//
//  Created by JP Giarrante on 09/09/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol EventRoutingLogic {}

protocol EventDataPassing {
    var dataStore: EventDataStore? { get }
}

final class EventRouter: NSObject, EventRoutingLogic, EventDataPassing {
    weak var viewController: EventViewController?
    var dataStore: EventDataStore?
}
