//
//  EventInteractor.swift
//  Eventize
//
//  Created by JP Giarrante on 09/09/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EventBusinessLogic {
    func doSomething(request: Event.Something.Request)
//    func doSomethingElse(request: Event.SomethingElse.Request)
}

protocol EventDataStore {
    //var name: String { get set }
}

class EventInteractor: EventBusinessLogic, EventDataStore {
    var presenter: EventPresentationLogic?
    var worker: EventWorker?
    //var name: String = ""

    // MARK: Do something (and send response to EventPresenter)

    func doSomething(request: Event.Something.Request) {
        worker = EventWorker()
        worker?.doSomeWork()

        let response = Event.Something.Response()
        presenter?.presentSomething(response: response)
    }
//
//    func doSomethingElse(request: Event.SomethingElse.Request) {
//        worker = EventWorker()
//        worker?.doSomeOtherWork()
//
//        let response = Event.SomethingElse.Response()
//        presenter?.presentSomethingElse(response: response)
//    }
}
