//
//  TicketsModels.swift
//  Eventize
//
//  Created by JP Giarrante on 09/09/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Tickets {
    enum TicketList {
        struct Request {}
        
        struct Response {
            let tickets: [TicketObject]
        }
        
        struct ViewModel {
            let tickets: [TicketObject]
        }
        
        struct CellViewModel {
            let ticket: TicketObject
        }
    }
    
    struct TicketObject: Codable {
        let date: String
        let isValid: Bool
        let eventUuid: String
        let title: String
        let description: String?
        let imageUrl: String?
        var quantity: Int?
        
        enum CodingKeys: String, CodingKey {
            case date
            case isValid = "is_valid"
            case eventUuid = "event_uuid"
            case title
            case description
            case imageUrl = "image_url"
            case quantity
        }
    }
    
    enum TicketFetchError: Error {
        case networkError
        case dataParsingError
    }
}
