//
//  TicketsPresenter.swift
//  Eventize
//
//  Created by JP Giarrante on 09/09/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TicketsPresentationLogic {
    func presentTickets(response: Tickets.TicketList.Response)
}

final class TicketsPresenter: TicketsPresentationLogic {
    weak var viewController: TicketsDisplayLogic?

    func presentTickets(response: Tickets.TicketList.Response) {
        viewController?.displayTickets(viewModel: .init(tickets: response.tickets))
    }
}
