//
//  TicketsPresenter.swift
//  Eventize
//
//  Created by JP Giarrante on 09/09/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TicketsPresentationLogic {
    func presentSomething(response: Tickets.Something.Response)
}

final class TicketsPresenter: TicketsPresentationLogic {
    weak var viewController: TicketsDisplayLogic?

    // MARK: Parse and calc respnse from TicketsInteractor and send simple view model to TicketsViewController to be displayed

    func presentSomething(response: Tickets.Something.Response) {
        let viewModel = Tickets.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
//
//    func presentSomethingElse(response: Tickets.SomethingElse.Response) {
//        let viewModel = Tickets.SomethingElse.ViewModel()
//        viewController?.displaySomethingElse(viewModel: viewModel)
//    }
}
