//
//  HomeInteractor.swift
//  Eventize
//
//  Created by JP Giarrante on 09/09/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic {
    func doSomething(request: Home.Something.Request)
//    func doSomethingElse(request: Home.SomethingElse.Request)
}

protocol HomeDataStore {
    //var name: String { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore {
    var presenter: HomePresentationLogic?
    var worker: HomeWorker?
    //var name: String = ""

    // MARK: Do something (and send response to HomePresenter)

    func doSomething(request: Home.Something.Request) {
        worker = HomeWorker()
        worker?.doSomeWork()

        let response = Home.Something.Response()
        presenter?.presentSomething(response: response)
    }
//
//    func doSomethingElse(request: Home.SomethingElse.Request) {
//        worker = HomeWorker()
//        worker?.doSomeOtherWork()
//
//        let response = Home.SomethingElse.Response()
//        presenter?.presentSomethingElse(response: response)
//    }
}
