//
//  EventsInteractor.swift
//  Eventize
//
//  Created by JP Giarrante on 09/09/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EventsBusinessLogic {
    func doSomething(request: Events.Something.Request)
//    func doSomethingElse(request: Events.SomethingElse.Request)
}

protocol EventsDataStore {
    //var name: String { get set }
}

class EventsInteractor: EventsBusinessLogic, EventsDataStore {
    var presenter: EventsPresentationLogic?
    var worker: EventsWorker?
    //var name: String = ""

    // MARK: Do something (and send response to EventsPresenter)

    func doSomething(request: Events.Something.Request) {
        worker = EventsWorker()
        worker?.doSomeWork()

        let response = Events.Something.Response()
        presenter?.presentSomething(response: response)
    }
//
//    func doSomethingElse(request: Events.SomethingElse.Request) {
//        worker = EventsWorker()
//        worker?.doSomeOtherWork()
//
//        let response = Events.SomethingElse.Response()
//        presenter?.presentSomethingElse(response: response)
//    }
}
