//
//  EventsModels.swift
//  Eventize
//
//  Created by JP Giarrante on 09/09/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Events {
    enum EventList {
        struct Request {
            let address: String?
            let term: String?
            
            init(address: String? = nil, term: String? = nil) {
                self.address = address
                self.term = term
            }
        }

        struct Response {
            let events: [EventObject]
        }
        
        struct ViewModel {
            let events: [EventObject]
        }
        
        struct CellViewModel {
            let event: EventObject
        }
    }
    
    struct EventObject: Codable {
        struct EventContent: Codable {
            struct BottomInfo: Codable {
                let imageUrl: String?
                let text: String
            }
            
            let imageUrl: String?
            let title: String
            let subtitle: String?
            let price: Double?
            let info: String?
            let extraBottomInfo: [BottomInfo]?
            
            private enum CodingKeys: String, CodingKey {
                case imageUrl = "image_url"
                case title
                case subtitle
                case price
                case info
                case extraBottomInfo = "extra_bottom_info"
            }
        }
        
        let eventUuid: String
        let content: EventContent
        
        private enum CodingKeys: String, CodingKey {
            case eventUuid = "event_uuid"
            case content
        }
    }
    
    enum EventFetchError: Error {
        case networkError
        case dataParsingError
    }
}
