//
//  EventsModels.swift
//  Eventize
//
//  Created by JP Giarrante on 09/09/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Events
{
    // MARK: Use cases

    enum EventList {
        struct Request {

        }

        struct Response {
            let events: [EventObject]
        }
        
        struct ViewModel {
            let events: [EventObject]
        }
        
        struct CellViewModel {
            struct Label {
                let image: UIImage?
                let text: String
            }
            
            let image: UIImage?
            let title: String
            let address: String
            let price: Double
            let extraInfo: String?
            let labels: [Label]?
        }
    }
    
    struct EventObject {
        let content: EventList.CellViewModel
    }
}
