//
//  EventsInteractor.swift
//  Eventize
//
//  Created by JP Giarrante on 09/09/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EventsBusinessLogic {
    func fetchEvents(request: Events.EventList.Request)
    func filterEvents(request: Events.EventList.Request)
    func selectEvent(at index: Int)
}

protocol EventsDataStore {
    var events: [Events.EventObject] { get set }
    var selectedEvent: Events.EventObject? { get set }
}

final class EventsInteractor: EventsBusinessLogic, EventsDataStore {
    var presenter: EventsPresentationLogic?
    var worker: EventsWorker
    
    var selectedEvent: Events.EventObject?
    var events: [Events.EventObject]
    
    init(presenter: EventsPresentationLogic? = nil,
         worker: EventsWorker = EventsWorker(),
         selectedEvent: Events.EventObject? = nil,
         events: [Events.EventObject] = []) {
        self.presenter = presenter
        self.worker = worker
        self.selectedEvent = selectedEvent
        self.events = events
    }

    // MARK: Do something (and send response to EventsPresenter)

    func fetchEvents(request: Events.EventList.Request) {
        worker.fetchEvents(completion: { [weak self] result in
            guard let self else { return }
            
            switch result {
            case .success(let events):
                self.events = events
                presenter?.presentEvents(response: .init(events: events))
            case .failure(_):
                // TODO: Error Handling!
                break
            }
        })
    }
    
    func filterEvents(request: Events.EventList.Request) {
        let filteredEvents = worker.filterEvents(events: events, searchTerm: request.term)
        presenter?.presentEvents(response: .init(events: filteredEvents))
    }
    
    func selectEvent(at index: Int) {
        selectedEvent = events[safe: index]
    }
}
